CREATE TABLE post (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    content VARCHAR(200) NOT NULL
);

CREATE TABLE comment (
    id INT AUTO_INCREMENT PRIMARY KEY,
    post_id BIGINT NOT NULL,
    content VARCHAR(200) NOT NULL,
    FOREIGN KEY (post_id) REFERENCES post(id)
);